name: flutter_cognitive_training_screens
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/digicas/flutter_cognitive_training_screens
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  levels_dart_pyramid_funnels:
    git: 
      url: https://github.com/digicas/levels_dart_pyramid_funnels.git
      ref: master
  on_screen_keyboard:
    git:
      url: https://github.com/digicas/flutter_minimalistic_onscreen_keyboard.git
      ref: master
  cvicebnice_overlays:
    git:
      url: https://github.com/digicas/flutter_cognitive_training_screens.git
      path: cvicebnice_overlays
      ref: master
      
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
